### PR TITLE
refactor: Simplified logging

### PR DESCRIPTION
**Pull request by gustavopsantos**
Reduces nesting on hooking while making it easier for future hooks to be added.

### CODE REVIEW

**Comment by TwoTenPvP** [comment]
Looks good. Thanks for this!

**Comment by TwoTenPvP** [comment]
Only concern I have is:

1. This is a breaking change due to the name change of CommonLoggers to UnityLoggers. Is it worth a major version bump?
2. In order for the CI to automatically check the commit type, release a new version etc you need to follow semantic commits. Could you fix please.


Thanks @gustavopsantos

**Comment by gustavopsantos** [comment]
`1 - This is a breaking change due to the name change of CommonLoggers to UnityLoggers. Is it worth a major version bump?`
Hmmm I didnt saw that, I dont think it is worth a major version bump, so Im gonna revert the field renaming I did.

`2 - In order for the CI to automatically check the commit type, release a new version etc you need to follow semantic commits. Could you fix please.`
Sure

**Comment by gustavopsantos** [comment]
@TwoTenPvP I have applied the fixes for the concerns you had 😉

**Comment by gustavopsantos** [comment]
@TwoTenPvP Theres something else I need to fix? Thanks,

**Pull request closed without merging**
